# Generated by Django 4.2.13 on 2024-06-30 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='formats',
        ),
        migrations.AlterField(
            model_name='album',
            name='album_img',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.CreateModel(
            name='AlbumFormat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discs.album')),
                ('format', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discs.format')),
            ],
        ),
    ]
