# Generated by Django 4.2.13 on 2024-06-30 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discs', '0002_remove_album_formats_alter_album_album_img_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='price',
        ),
    ]
