# Generated by Django 4.2.13 on 2024-06-30 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discs', '0003_remove_album_price'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='albumformat',
            constraint=models.UniqueConstraint(fields=('album', 'format'), name='unique_album_format'),
        ),
    ]
