# Generated by Django 4.2.13 on 2024-07-10 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discs', '0006_artist_alter_album_artist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'ordering': ['title']},
        ),
        migrations.AlterField(
            model_name='song',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
